### ISSUE TITLE
Rendering no fonts

### ISSUE THREAD

**Issue by razzeee** [flathub/com.microsoft.Edge#305] opened 2023-04-21 06:44 UTC
It seems like edge and therefore PWA's you use it for (like teams) don't render any text anymor.

![image](https://user-images.githubusercontent.com/5943908/233560700-485b9d7b-34af-4e45-ad8b-348bdb80af62.png)

Tested with fedora 38

**Comment by razzeee** [comment] 2023-04-21 06:46
Seems to work again after deleting/moving `~/.var/app/com.microsoft.Edge`

**Comment by evan-a-a** [comment] 2023-04-27 17:36
There were some issues in the Freedesktop runtime that could've been the cause of this. It has been fixed as of 22.08.11

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1576

**Closed** 2023-04-27 17:56 UTC
