### ISSUE TITLE
Global Menu does not appear in KDE, does in traditional Edge

### ISSUE THREAD

**Issue by WittyNameHere** [flathub/com.microsoft.Edge#100] opened 2021-12-17 22:52 UTC
The Edge installation from Microsoft includes support for KDE's Global Menu Plasmoid, allowing MacOS-style menus of File, Edit, History, etc. These don't appear when running the FlatPak, likely due to some configuration in the JSON file. Following [this advice](https://www.reddit.com/r/kde/comments/pa6bxz/tip_enable_the_global_menu_for_flatpaks/) and enabling some special permissions in FlatSeal causes the menu to appear momentarily when starting the app and then disappear when it's fully loaded, so something about the Flatpak's configuration is blocking these menus from appearing.

I hate to be the irritating KDE person, but some of us really love the global menu (particularly those of us who theme the biggest Mac knockoffs), and it would be nice if the Flatpak behaved identical to DEB/RPM Edge as far as the UX/UI.

To add system details: Plasma 5.23, Fedora 35

**Comment by TheEvilSkeleton** [comment] 2021-12-18 03:56
No worries, you're not being irritant. If anything you give the impression that you are the opposite. Your sentences are very well structured, you did your research before opening an issue and didn't yell at us.

I opened https://github.com/flathub/com.microsoft.Edge/pull/101 to support global menus. At the moment I followed the advice you linked, but of course it's far from working as intended.

I don't use Plasma so I can't really test global menus sadly. Can you install the test Flatpak by running `flatpak install https://dl.flathub.org/build-repo/69199/com.microsoft.Edge.flatpakref`? Afterwards, can you run `flatpak run --session-bus com.microsoft.Edge//test`, test a bit the application, and then check for the lines with `Failed to get the ownership of`?

For example:
```
[2:42:1217/225353.544566:ERROR:bus.cc(560)] Failed to get the ownership of org.mpris.MediaPlayer2.edge.instance2: org.freedesktop.DBus.Error.ServiceUnknown
```

The commands I provided are not intended to work. They should make troubleshooting easier.

**Comment by WittyNameHere** [comment] 2021-12-21 01:57
On Fri, Dec 17 2021 at 07:57:09 PM -0800, TheEvilSkeleton 
***@***.***> wrote:
> Afterwards, can you run flatpak run --session-bus 
> com.microsoft.Edge//test, test a bit the application, and then check 
> for the lines with Failed to get the ownership of?
> 

There is no such lines. Here's what I get:

> $ flatpak run --session-bus com.microsoft.Edge//test
> [2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child 
> - /app/extra/msedge --type=zygote --enable-crashpad 
> --crashpad-handler-pid=14 --enable-crash-reporter=,beta 
> --change-stack-guard-on-fork=enable
> Stub sandbox ignoring command: /app/extra/nacl_helper
> [2:2:1220/175248.227565:ERROR:nacl_fork_delegate_linux.cc(329)] Bad 
> NaCl helper startup ack (0 bytes)
> Opening in existing browser session.
> $

Note that I can't change permissions in Flatseal easily with the test 
build as Flatseal does not detect it for whatever reason.

**Comment by WittyNameHere** [comment] 2021-12-21 19:29
As of today's update to the Beta channel (97.0.1072.41-1), menus are now working. Thanks for listening.

**Comment by TheEvilSkeleton** [comment] 2021-12-21 20:37
Interesting. Does it work without https://github.com/flathub/com.microsoft.Edge/pull/101? Can you run `flatpak remove com.microsoft.Edge//test` and test it again?

**Comment by WittyNameHere** [comment] 2021-12-21 20:40
Yes, I have removed the test version and the menus are still sticking. Menus never appeared during my time using the test version (though I got the impression they weren't expected to.)

**Comment by TheEvilSkeleton** [comment] 2021-12-21 21:03
Reopened per https://github.com/flathub/com.microsoft.Edge/issues/104#issuecomment-999090197.

**Comment by WittyNameHere** [comment] 2021-12-21 22:01
Removed the test build from the other day and reinstalled it. Menus are there, and persisted after logging out and logging in. I'm going to keep using the test build for a while unless you want me to try anything else and see if they stick around.

**Comment by TheEvilSkeleton** [comment] 2021-12-21 22:16
Okay, I just want to be clear that I understand correctly. The test build is working as intended whereas the current does not. Is that correct?

**Comment by WittyNameHere** [comment] 2021-12-21 22:17
Correct.

**Comment by TheEvilSkeleton** [comment] 2021-12-21 22:19
Alright, I'm going to close this issue, per https://github.com/flathub/com.microsoft.Edge/pull/101.

**Closed** 2021-12-21 22:19 UTC

**Comment by TheEvilSkeleton** [comment] 2021-12-21 22:20
In more or less 4 hours, you should get a new update. Afterwards you can update and remove the test build.
