### ISSUE TITLE
Widevine missing or not working

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.microsoft.Edge#8] opened 2021-02-01 16:09 UTC
![image](https://user-images.githubusercontent.com/50847364/106484790-f17b2080-647d-11eb-898d-4d5c5bc3d25f.png)

Related to https://github.com/flathub/com.brave.Browser/issues/10.

**Comment by rowbawts** [comment] 2021-09-06 17:43
I'm seeing this issue on the latest build, I'll admit it's not high priority for me as I don't use Netflix all that much and even when I do it's usually on my TV but I thought I'd bring it up as I'm not sure if this was closed as solved.

**Comment by TheEvilSkeleton** [comment] 2021-09-06 17:45
It was fixed for a bit, probably switching to the beta version caused this.

**Comment by TheEvilSkeleton** [comment] 2021-09-06 22:32
Odd, I just realized that it should've worked https://github.com/flathub/com.microsoft.Edge/blob/0ddc0438d6425d31cf34a991b844e93910eb1a5d/com.microsoft.Edge.yaml#L14.

**Comment by TheEvilSkeleton** [comment] 2021-09-06 22:42
@refi64 do you know what would cause this?

**Comment by refi64** [comment] 2021-09-06 23:18
@rowbawts does https://bitmovin.com/demos/drm display properly and say it's using "Widevine" for you?

**Comment by rowbawts** [comment] 2021-09-07 04:28
> @rowbawts does https://bitmovin.com/demos/drm display properly and say it's using "Widevine" for you?

Seems like it so is Netflix just blocking the User Agent (Linux)?

![Screenshot from 2021-09-07 00-27-20](https://user-images.githubusercontent.com/13012832/132284359-0bb50f59-38b4-4f10-8859-a3d34ae337c1.png)

**Comment by rowbawts** [comment] 2021-09-15 10:41
So I did some testing it seems like the User agent is all it is, if I switch to a Firefox Windows 10 User agent it works perfectly.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-23 22:01
> http://github.com/flathub/com.microsoft.Edge/issues/8#issuecomment-919906579

Thus, this issue should be closed.

**Comment by refi64** [comment] 2021-09-27 16:39
After looking into this more, I can reproduce the issue on a native Edge installation, thus I don't believe this is a Flatpak-related issue.

**Closed** 2021-09-27 18:05 UTC

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-27 18:25
Is http://github.com/flathub/com.brave.Browser/pull/16 applicable to [this](http://github.com/flathub/com.microsoft.Edge/issues/8)?

**Comment by refi64** [comment] 2021-09-27 18:49
No, because one of the above comments shows that Widevine itself works. Netflix tends to have issues because its user agent detection for Edge results in it trying to use PlayReady instead of Widevine, so Edge itself hacks around it (but the hacks have probably broken).

-- Ryan
https://refi64.com/
