### ISSUE TITLE
Fails to launch on Fedora 38

### ISSUE THREAD

**Issue by PJansky** [flathub/com.microsoft.Edge#304] opened 2023-04-20 17:00 UTC
Edge 112.0.1722.54-1 stable fails to launch on Fedora 38 installed from the Fedora Flathub Selection Repo, possibly a problem on their part.

`flatpak run com.microsoft.Edge --verbose
 Stub sandbox ignoring command: /app/extra/nacl_helper
 [2:2:0420/185219.271456:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
 [0420/185219.282738:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)`

**Comment by Zeit08** [comment] 2023-04-20 18:46
Same. Also Brave browser fails to launch, but with another error. I do not know if Edge and Brave are related, though.

**Comment by dominikzogg** [comment] 2023-04-20 20:20
Same here, uninstalled, installed with `flatpak install flathub com.microsoft.Edge` and deleted ` .var/app/com.microsoft.Edge`, same issue

**Comment by PJansky** [comment] 2023-04-20 20:51
I quickly played around the this in a view VMs I had laying around. Arch doesn't seem to be affected, I could only reproduce this in Fedora 38. Edge Dev (114.0.1793.0-1), Chrome and Chrome Dev all work with the exception beeing Brave, which is also broken as @Zeit08 already mentioned.

**Comment by daegalus** [comment] 2023-04-20 21:33
I know this isn't related to the flatpak, but Edge is getting segfaults on F37 and F38 on the latest version from their RPM repos. So it might be a dependency change. It was working fine, I did an update on F37 and it broke. Then upgraded to F38 with no changes.

Again, I realize this isn't related to the flatpak, but might lead to the cause.

**Comment by moljac024** [comment] 2023-04-20 23:26
Can you all check if it doesn't crash when you run it from the terminal?
I am on Fedora Silverblue 38 right now and experience the crash on startup, but if I run it from the terminal (`flatpak run com.microsoft.Edge`) it doesn't crash! It's very weird and surprising.

**Comment by daegalus** [comment] 2023-04-20 23:33
Non-silverblue: fails to start on Flatpak cli run.

**Comment by dominikzogg** [comment] 2023-04-21 05:19
I can agree, that it's not failing on all off my fedora 38 installations (weired), only on 1 so far (checked two, so 50%).

**Comment by zxcq** [comment] 2023-04-21 07:22
Downgraded to 
`flatpak update com.microsoft.Edge --commit ed85cc7715ef4ace3c33409da8dfcbd5300f22c3400ff5fe830e382eed457ded`
and working for now

**Comment by karlabbott** [comment] 2023-04-21 11:22
Can also confirm that I'm hitting this on Fedora 37 Silverblue. Also @zxcq 's workaround in https://github.com/flathub/com.microsoft.Edge/issues/304#issuecomment-1517385160 works for me.

**Comment by evan-a-a** [comment] 2023-04-21 15:14
I can't reproduce on either of my F38 Silverblue machines. The base system is up-to-date as of Monday and have `org.freedesktop.Platform` version 22.08.11 installed.

**Comment by evan-a-a** [comment] 2023-04-21 15:18
Actually, scratch that. I can reproduce after removing `~/.var/app/com.microsoft.Edge`

**Comment by evan-a-a** [comment] 2023-04-21 15:42
I did some light debugging, and it appears it's crashing somewhere inside of `msedge` with `SIGILL`. Given the lack of debug symbols it might be tricky to track down exactly what's causing this.

**Comment by gavrilovegor519** [comment] 2023-04-21 15:51
I'm also have a SIGILL error. On Ubuntu Edge (DEB  package) is working, but on some websites I'm also get a SIGILL, but only on page tab (browser not crashing). On Fedora Workstation 38 this error I get on launch.

**Comment by evan-a-a** [comment] 2023-04-21 19:15
Edge 113 beta doesn't appear to have these issues. Instead of attempting to debug the issues with 112, the best course of action may be to wait until its release on May 4th.

**Comment by refi64** [comment] 2023-04-21 19:57
These messages are generally entirely normal:

```
Stub sandbox ignoring command: /app/extra/nacl_helper
[2:2:0421/071947.073005:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
[0421/071947.241819:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
```

and likely unrelated to anything going on here.

If someone wants to have a bit of an Adventure, you can use `coredumpctl debug` to access the core dump in a debugger, then use `disas` to get the 100 or so surrounding instructions and post them here. (ngl I forgot most of the exact syntax, it's been a while :sweat_smile:)

**Comment by mysticaltech** [comment] 2023-04-23 08:07
Hey folks, just FYI (and thanks @evan-a-a for the tip, and I use edge installed via dnf on Fedora 38 between), after installing Microsoft Edge Beta, the normal one opens again! Yep neat trick lol.

**Comment by daegalus** [comment] 2023-04-24 16:23
> Hey folks, just FYI (and thanks @evan-a-a for the tip, and I use edge installed via dnf on Fedora 38 between), after installing Microsoft Edge Beta, the normal one opens again! Yep neat trick lol.

Unfortunately not on my end. Im still getting invalid hardware instruction segfaults

**Comment by mysticaltech** [comment] 2023-04-24 18:10
> > Hey folks, just FYI (and thanks @evan-a-a for the tip, and I use edge installed via dnf on Fedora 38 between), after installing Microsoft Edge Beta, the normal one opens again! Yep neat trick lol.
> 
> ~Unfortunately not on my end. Im still getting invalid hardware instruction segfaults~
> 
> Scratch that, I had to start the beta version, then the stable version works fine.
> 
> [Edit] Well even though it launches, I am getting SIGILL in my tabs.

Weird, on my end, I have syncing turned on, and I let the beta sync completely first, then did not uninstall it, left it on the system, and stable runs fine, writing for it now.

**Comment by joesizzlin** [comment] 2023-04-30 17:06
can confirm same issue related to most recent stable release
fedora 38 workstation

**Comment by huyhoang160593** [comment] 2023-04-30 19:20
same issue with fedora 38 workstation. The only possible way of open edge is via using terminal to open the app directly. Any attempt to run in the desktop will make the edge windown run in about 5s and then crash with no log

**Comment by mysticaltech** [comment] 2023-05-01 07:30
I get weird SIGKill on some tabs for some websites like namesilo.com.

**Comment by TheEvilSkeleton** [comment] 2023-05-08 03:28
I doubt I can do anything on my end. That being said, this might have been fixed in Edge Dev https://github.com/flathub/com.microsoft.EdgeDev/issues/5#issuecomment-1533960442

I'll keep it open until Microsoft resolves it in the stable version

**Comment by mysticaltech** [comment] 2023-05-08 09:36
@GreenCappuccino Thanks for the info, now that makes sense!

@TheEvilSkeleton Thanks for looking into this too. Actually, we will have it even sooner as it's working on Beta, so 113 (Dev is 114), if I am not mistaken.

**Comment by mysticaltech** [comment] 2023-05-08 20:09
> I'm on Fedora 38 (SilverBlue), don't have that issue (just installed), using the normal edge with no issues.

Try visiting https://namesilo.com for instance, and let us know if you get a SIGKILL please.

**Comment by rtmor** [comment] 2023-05-08 21:08
> > I'm on Fedora 38 (SilverBlue), don't have that issue (just installed), using the normal edge with no issues.
> 
> Try visiting https://namesilo.com for instance, and let us know if you get a SIGKILL please.

Received SIGKILL while visiting that URL (in addition to several others) on version `112.0.1722.64 (Official build) (64-bit)`. Just updated to `113.0.1774.35 (Official build) (64-bit)` and no longer experiencing any issues for that URL.

Fedora 38 (Silverblue) here, as well.

**Comment by abuturabofficial** [comment] 2023-05-09 03:31
> I'm on Fedora 38 (SilverBlue), don't have that issue (just installed), using the normal edge with no issues.

An update to this, it does crashes when I first launch it, but reopening it, then works normally. Currently, don't have a time to debug, what's really happening.(Edge is not even my main browser, so can live with it like that for some time)

**Comment by richpurnellai** [comment] 2023-05-09 12:49
The Edge version I am currently using is `113.0.1774.35-1`, and all crash issues have disappeared.

**Comment by abuturabofficial** [comment] 2023-05-09 13:18
> The Edge version I am currently using is `113.0.1774.35-1`, and all crash issues have disappeared.

I have downloaded this version yesterday, and started facing the issues.

```
Open Edge > Crashes > Reopen > Everything Normal
```

**Comment by evan-a-a** [comment] 2023-10-07 17:01
This is likely resolved per comments above.

**Closed by evan-a-a** 2023-10-07 17:01 UTC
