### ISSUE TITLE
I'm also have a #304 issue.

### ISSUE THREAD

**Issue by gavrilovegor519** [flathub/com.microsoft.Edge#306] opened 2023-04-21 15:54 UTC
Fedora Workstation 38 (Flatpak version): I'm get SIGILL on launch.
Ubuntu 22.04 (DEB version): I'm get SIGILL in tab on some websites.

**Comment by TheEvilSkeleton** [comment] 2023-04-21 18:01
Duplicate of #304

**Closed by TheEvilSkeleton** 2023-04-21 18:01 UTC
